import type { ProvisioningContext } from './types.js';

/**
 * Render the per-instance docker-compose file.
 *
 * Security posture, in order of importance:
 *   1. NO PUBLISHED PORTS. Postgres, Redis, backend and frontend are all
 *      internal-only. The shop is reached exclusively through the shared
 *      Traefik edge proxy on the host. Publishing 5432 would put every
 *      shop's database on the open internet.
 *   2. Credentials come from .env, never inlined here.
 *   3. Resource caps, so one runaway shop cannot starve its neighbours on
 *      a shared host.
 *   4. Health checks, so the provisioner knows what "ready" means rather
 *      than guessing with a fixed sleep.
 */
export function renderComposeFile(ctx: ProvisioningContext): string {
  const project = `retailos-${ctx.shortId}`;
  const labels = [
    `    labels:`,
    `      - "retailos.project=${project}"`,
    `      - "retailos.instance=${ctx.instanceId}"`,
    `      - "retailos.version=${ctx.version}"`,
  ].join('\n');

  return `# Generated by Retail OS control plane. Do not edit by hand.
# Instance: ${ctx.instanceId} (${ctx.shortId})
# Business: ${ctx.businessName}
# Version: ${ctx.version}
#
# No ports are published. This instance is reachable only through the
# Traefik edge proxy on ${ctx.host.name}.

name: ${project}

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      # Deterministic collation for receipt ordering.
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: ${ctx.resourceMemoryMb ?? 1024}M
    networks: [retailos]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "\${REDIS_PASSWORD}", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256M
    networks: [retailos]

  backend:
    image: \${BACKEND_IMAGE}
    restart: unless-stopped
    env_file: [.env]
    environment:
      NODE_ENV: production
      PORT: "4000"
      DATABASE_URL: postgresql://shop:\${POSTGRES_PASSWORD}@postgres:5432/shop
      DIRECT_URL: postgresql://shop:\${POSTGRES_PASSWORD}@postgres:5432/shop
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:4000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
    networks: [retailos]

  frontend:
    image: \${FRONTEND_IMAGE}
    restart: unless-stopped
    env_file: [.env]
    environment:
      PUBLIC_URL: \${PUBLIC_URL}
      API_BASE: http://backend:4000
    depends_on:
      backend:
        condition: service_healthy
${labels}
    deploy:
      resources:
        limits:
          memory: 256M
    networks: [retailos]

networks:
  retailos:
    name: retailos_${ctx.instanceId.replace(/-/g, '').slice(0, 12)}
    driver: bridge

volumes:
  postgres_data:
  redis_data:
`;
}
