/**
 * Generates apps/shop_pos/lib/shared/icons.dart (the AppIcons mapping layer)
 * by resolving every concept in scripts/icon-map.mjs against the Lucide
 * package that is actually installed. Nothing is guessed: if a concept has no
 * matching Lucide icon the script lists it and exits without writing.
 *
 * Prerequisite (once):  cd apps/shop_pos && flutter pub add lucide_icons_flutter
 * Run from repo root:   node scripts/gen-icons.mjs
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { ICON_MAP, MATERIAL_TO_SEMANTIC } from './icon-map.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const appDir = join(root, 'apps', 'shop_pos');
const outFile = join(appDir, 'lib', 'shared', 'icons.dart');
const PKG = 'lucide_icons_flutter';

function fail(msg) {
  console.error(`[gen-icons] ${msg}`);
  process.exit(1);
}

// 1. Locate the installed package via the resolved package config.
const cfgPath = join(appDir, '.dart_tool', 'package_config.json');
if (!existsSync(cfgPath)) fail('apps/shop_pos/.dart_tool/package_config.json not found. Run `flutter pub get` in apps/shop_pos.');
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));
const pkg = cfg.packages.find((p) => p.name === PKG);
if (!pkg) fail(`${PKG} is not a dependency yet. Run: cd apps/shop_pos && flutter pub add ${PKG}`);

const rootUri = pkg.rootUri.endsWith('/') ? pkg.rootUri : `${pkg.rootUri}/`;
const pkgRoot = new URL(rootUri, pathToFileURL(cfgPath));
const libDir = fileURLToPath(new URL(pkg.packageUri ?? 'lib/', pkgRoot));

function walk(dir) {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : p.endsWith('.dart') ? [p] : [];
  });
}

// 2. Collect the icon identifiers from the file that defines LucideIcons.
const iconFiles = walk(libDir).filter((f) => /class\s+LucideIcons\b/.test(readFileSync(f, 'utf8')));
if (!iconFiles.length) fail(`No "class LucideIcons" found under ${libDir}. The package layout may have changed; paste me the contents of its lib/ folder.`);

const names = new Set();
for (const f of iconFiles) {
  for (const m of readFileSync(f, 'utf8').matchAll(/static\s+const\s+\w+\s+(\w+)\s*=/g)) names.add(m[1]);
}
if (names.size < 100) fail(`Only found ${names.size} icon identifiers in ${iconFiles[0]}; expected 1000+. Parsing needs adjusting.`);

const importPath = `package:${PKG}/${relative(libDir, iconFiles[0]).replaceAll('\\', '/')}`;
const lower = new Map([...names].map((n) => [n.toLowerCase(), n]));
console.log(`[gen-icons] ${names.size} Lucide icons found; importing ${importPath}`);

// 3. Resolve every concept.
const resolved = [];
const unresolved = [];
for (const [sem, cands] of ICON_MAP) {
  const hit = cands.find((c) => names.has(c)) ?? cands.map((c) => lower.get(c.toLowerCase())).find(Boolean);
  if (hit) resolved.push([sem, hit]);
  else unresolved.push([sem, cands]);
}

// 4. Check that every icon the app really uses is covered by the map.
const usedPath = join(root, 'docs', 'ui-uplift', 'icons-used.json');
if (existsSync(usedPath)) {
  const used = JSON.parse(readFileSync(usedPath, 'utf8')).icons
    .map((i) => i.name)
    .filter((n) => n.startsWith('Icons.'))
    .map((n) => n.slice('Icons.'.length));
  const unmapped = used.filter((m) => !MATERIAL_TO_SEMANTIC.has(m));
  if (unmapped.length) console.warn(`[gen-icons] Material icons used in the app but missing from icon-map.mjs: ${unmapped.join(', ')}`);
}

if (unresolved.length) {
  console.error('\n[gen-icons] No Lucide match for these concepts (nothing written):');
  for (const [sem, cands] of unresolved) {
    const stem = cands[0].toLowerCase().slice(0, 4);
    const near = [...names].filter((n) => n.toLowerCase().includes(stem)).slice(0, 10);
    console.error(`  ${sem}: tried [${cands.join(', ')}]  similar: [${near.join(', ')}]`);
  }
  console.error('\nAdd a working name to the candidates in scripts/icon-map.mjs and re-run.');
  process.exit(1);
}

// 5. Emit.
const body = resolved
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([sem, lucide]) => `  static const IconData ${sem} = LucideIcons.${lucide};`)
  .join('\n');

const dart = `// AUTO-GENERATED by scripts/gen-icons.mjs from scripts/icon-map.mjs
// Do not edit by hand. To change an icon, edit icon-map.mjs and re-run:
//   node scripts/gen-icons.mjs
//
// The single mapping layer between the app and the icon set. Views use
// AppIcons.<concept> and never import Lucide directly, so swapping the icon
// set later is a one-file change.

import 'package:flutter/widgets.dart';
import '${importPath}';

class AppIcons {
  const AppIcons._();

${body}
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, dart);
console.log(`[gen-icons] wrote ${resolved.length} icons -> ${outFile}`);
