// AUTO-GENERATED by scripts/gen-icons.mjs from scripts/icon-map.mjs
// Do not edit by hand. To change an icon, edit icon-map.mjs and re-run:
//   node scripts/gen-icons.mjs
//
// The single mapping layer between the app and the icon set. Views use
// AppIcons.<concept> and never import Lucide directly, so swapping the icon
// set later is a one-file change.

import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class AppIcons {
  const AppIcons._();

  static const IconData add = LucideIcons.plus;
  static const IconData addCircle = LucideIcons.circlePlus;
  static const IconData addToCart = LucideIcons.shoppingCart;
  static const IconData analytics = LucideIcons.chartLine;
  static const IconData arrowBack = LucideIcons.arrowLeft;
  static const IconData arrowDown = LucideIcons.arrowDown;
  static const IconData arrowForward = LucideIcons.arrowRight;
  static const IconData arrowUp = LucideIcons.arrowUp;
  static const IconData baby = LucideIcons.baby;
  static const IconData backspace = LucideIcons.delete;
  static const IconData bag = LucideIcons.shoppingBag;
  static const IconData bakery = LucideIcons.croissant;
  static const IconData bank = LucideIcons.landmark;
  static const IconData barChart = LucideIcons.chartColumn;
  static const IconData barcodeReader = LucideIcons.scanBarcode;
  static const IconData basket = LucideIcons.shoppingBasket;
  static const IconData beauty = LucideIcons.flower2;
  static const IconData bolt = LucideIcons.zap;
  static const IconData book = LucideIcons.book;
  static const IconData business = LucideIcons.building2;
  static const IconData cart = LucideIcons.shoppingCart;
  static const IconData check = LucideIcons.check;
  static const IconData checkCircle = LucideIcons.circleCheck;
  static const IconData chevronRight = LucideIcons.chevronRight;
  static const IconData clean = LucideIcons.sparkles;
  static const IconData close = LucideIcons.x;
  static const IconData cloudDone = LucideIcons.cloudCheck;
  static const IconData cloudOff = LucideIcons.cloudOff;
  static const IconData cloudSync = LucideIcons.cloudSync;
  static const IconData copy = LucideIcons.copy;
  static const IconData creditCard = LucideIcons.creditCard;
  static const IconData delete = LucideIcons.trash2;
  static const IconData deleteForever = LucideIcons.trash2;
  static const IconData deleteSweep = LucideIcons.trash2;
  static const IconData download = LucideIcons.download;
  static const IconData drink = LucideIcons.cupSoda;
  static const IconData dropDown = LucideIcons.chevronDown;
  static const IconData edit = LucideIcons.pencil;
  static const IconData egg = LucideIcons.egg;
  static const IconData error = LucideIcons.circleAlert;
  static const IconData grain = LucideIcons.wheat;
  static const IconData health = LucideIcons.heartPulse;
  static const IconData home = LucideIcons.house;
  static const IconData iceCream = LucideIcons.iceCreamCone;
  static const IconData info = LucideIcons.info;
  static const IconData inventory = LucideIcons.package;
  static const IconData layers = LucideIcons.layers;
  static const IconData link = LucideIcons.link;
  static const IconData lock = LucideIcons.lock;
  static const IconData lockClock = LucideIcons.clock;
  static const IconData lockOpen = LucideIcons.lockOpen;
  static const IconData manageAccounts = LucideIcons.userCog;
  static const IconData meat = LucideIcons.drumstick;
  static const IconData menu = LucideIcons.menu;
  static const IconData money = LucideIcons.coins;
  static const IconData notes = LucideIcons.stickyNote;
  static const IconData oil = LucideIcons.droplet;
  static const IconData payments = LucideIcons.banknote;
  static const IconData people = LucideIcons.users;
  static const IconData person = LucideIcons.user;
  static const IconData personAdd = LucideIcons.userPlus;
  static const IconData pet = LucideIcons.pawPrint;
  static const IconData phone = LucideIcons.phone;
  static const IconData phoneAndroid = LucideIcons.smartphone;
  static const IconData photoAdd = LucideIcons.imagePlus;
  static const IconData photoLibrary = LucideIcons.images;
  static const IconData playCircle = LucideIcons.circlePlay;
  static const IconData pos = LucideIcons.calculator;
  static const IconData print = LucideIcons.printer;
  static const IconData produce = LucideIcons.leaf;
  static const IconData qrCode = LucideIcons.qrCode;
  static const IconData qrScanner = LucideIcons.scanLine;
  static const IconData receipt = LucideIcons.receipt;
  static const IconData receiptLong = LucideIcons.receiptText;
  static const IconData remove = LucideIcons.minus;
  static const IconData removeCircle = LucideIcons.circleMinus;
  static const IconData removeFromCart = LucideIcons.shoppingCart;
  static const IconData restart = LucideIcons.rotateCcw;
  static const IconData rice = LucideIcons.soup;
  static const IconData save = LucideIcons.save;
  static const IconData search = LucideIcons.search;
  static const IconData send = LucideIcons.send;
  static const IconData settings = LucideIcons.settings;
  static const IconData share = LucideIcons.share2;
  static const IconData shield = LucideIcons.shield;
  static const IconData shipping = LucideIcons.truck;
  static const IconData snack = LucideIcons.sandwich;
  static const IconData storage = LucideIcons.database;
  static const IconData storefront = LucideIcons.store;
  static const IconData swapHoriz = LucideIcons.arrowLeftRight;
  static const IconData swapVert = LucideIcons.arrowUpDown;
  static const IconData sync = LucideIcons.refreshCw;
  static const IconData tag = LucideIcons.tag;
  static const IconData tethering = LucideIcons.radio;
  static const IconData tool = LucideIcons.wrench;
  static const IconData trendingDown = LucideIcons.trendingDown;
  static const IconData trendingUp = LucideIcons.trendingUp;
  static const IconData tune = LucideIcons.slidersHorizontal;
  static const IconData undo = LucideIcons.undo2;
  static const IconData upload = LucideIcons.upload;
  static const IconData verified = LucideIcons.badgeCheck;
  static const IconData visibility = LucideIcons.eye;
  static const IconData visibilityOff = LucideIcons.eyeOff;
  static const IconData vpnKey = LucideIcons.keyRound;
  static const IconData wallet = LucideIcons.wallet;
  static const IconData wallpaper = LucideIcons.image;
  static const IconData warning = LucideIcons.triangleAlert;
  static const IconData waterDrop = LucideIcons.droplet;
}
